In [5]:
import pandas as pd
import numpy as np
from dateutil.parser import parse

In [6]:
#Sheet nov2019_Mg_PS

#Step1: Load the Data for the month
df_nov2019_Mg_PS =  pd.read_excel(r'C:\Users\v.t.flores\Documents\Analysis_November2019_MSdataCLEAN.xlsx', sheet_name='NOV19Datetime_Mg_PS', index_col=False)

#Step2: Parse the DATETIME column
df_nov2019_Mg_PS['DATETIME'] = df_nov2019_Mg_PS['DATETIME'].apply(lambda x: parse(str(x)))

#Step3: Set the DATETIME column as the index
df_nov2019_Mg_PS.set_index('DATETIME', inplace=True)

print('DONE. nov2019_Mg_PS')

DONE. nov2019_Mg_PS


In [7]:
#Sheet 106FT02A_spcl

#Step1: Load the Data for the month
df_106FT02A_spcl =  pd.read_excel(r'C:\Users\v.t.flores\Documents\Analysis_November2019_MSdataCLEAN.xlsx', sheet_name='106FT02A_spcl', index_col=False)

#Step2: Parse the DATETIME column
df_106FT02A_spcl['DATETIME'] = df_106FT02A_spcl['DATETIME'].apply(lambda x: parse(x))

#Step3: Set the DATETIME column as the index
df_106FT02A_spcl.set_index('DATETIME', inplace=True)

print('DONE. 106FT02A_spcl')

DONE. 106FT02A_spcl


In [8]:
#Sheet 106FT02B_spcl

#Step1: Load the Data for the month
df_106FT02B_spcl = pd.read_excel(r'C:\Users\v.t.flores\Documents\Analysis_November2019_MSdataCLEAN.xlsx', sheet_name='106FT02B_spcl', index_col=False)



#Step2: Parse the DATETIME column
df_106FT02B_spcl['DATETIME'] = df_106FT02B_spcl['DATETIME'].apply(lambda x: parse(x))

#Step3: Set the DATETIME column as the index
df_106FT02B_spcl.set_index('DATETIME', inplace=True)

print('DONE. 106FT02B_spcl')

DONE. 106FT02B_spcl


In [9]:
#Sheet From Pi
#Step1: Load the Data for the month
df_nov2019Pi = pd.read_excel(r'C:\Users\v.t.flores\Documents\Analysis_November2019_MSdataCLEAN.xlsx', sheet_name='From Pi', index_col=False)

#Drop the row[1]
df_nov2019Pi = df_nov2019Pi.drop(df_nov2019Pi.index[0])

#Step2: Parse the DATETIME column
df_nov2019Pi['DATETIME'] = df_nov2019Pi['DATETIME'].apply(lambda x: parse(str(x)))

df_nov2019Pi.set_index('DATETIME', inplace=True)

print('Done')

Done


In [210]:
df_com_Pi_FT02A = df_nov2019Pi.join(df_106FT02A_spcl, how='outer')

In [211]:
df_com_Mg_FT02B = df_nov2019_Mg_PS.join(df_106FT02B_spcl, how='outer')

In [212]:
df_comb = df_com_Pi_FT02A.join(df_com_Mg_FT02B, how='outer')

In [177]:
df_comb.head()

A_t_CWSH1 B_t_CWSH1 A_t_CWSH2 B_t_CWSH2 A_t_DRY B_t_DRY  \
DATETIME                                                                      
2019-11-01 00:00:00        45       100        85       140     240     170   
2019-11-01 00:01:00        45       100        85       140     240     170   
2019-11-01 00:02:00        45       100        85       140     240     170   
2019-11-01 00:03:00        45       100        85       140     240     170   
2019-11-01 00:04:00        45       100        85       140     240      30   

                    A_t_FEED B_t_FEED A_t_PRESS1 A_t_PRESS2  ... B_Ca B_Si  \
DATETIME                                                     ...             
2019-11-01 00:00:00      440      399        185        180  ...  NaN  NaN   
2019-11-01 00:01:00      440      399         29        180  ...  NaN  NaN   
2019-11-01 00:02:00      440      399         85        180  ...  NaN  NaN   
2019-11-01 00:03:00      440      399        141        180  ...  NaN  NaN   
2019-11-01 00:04:00      440      399        185        180  ...  NaN  NaN   

                    B_Al B_Mg B_S B_%Moisture B_PS10 B_PS50 B_PS90 B_PSMEAN  
DATETIME                                                                     
2019-11-01 00:00:00  NaN  NaN NaN         NaN    NaN    NaN    NaN      NaN  
2019-11-01 00:01:00  NaN  NaN NaN         NaN    NaN    NaN    NaN      NaN  
2019-11-01 00:02:00  NaN  NaN NaN         NaN    NaN    NaN    NaN      NaN  
2019-11-01 00:03:00  NaN  NaN NaN         NaN    NaN    NaN    NaN      NaN  
2019-11-01 00:04:00  NaN  NaN NaN         NaN    NaN    NaN    NaN      NaN  

[5 rows x 67 columns]

In [168]:
df_com_Mg_FT02B.columns

Index(['TH01UF_Mg', 'TH01UF_g/ml', 'TH01UF_PS50', 'B_Pb', 'B_Zn', 'B_Cu',
       'B_Ni', 'B_Co', 'B_Fe', 'B_Mn', 'B_Cr', 'B_Ca', 'B_Si', 'B_Al', 'B_Mg',
       'B_S', 'B_%Moisture', 'B_PS10', 'B_PS50', 'B_PS90', 'B_PSMEAN'],
      dtype='object')

In [169]:
df_com_Pi_FT02A.columns

Index(['A_t_CWSH1', 'B_t_CWSH1', 'A_t_CWSH2', 'B_t_CWSH2', 'A_t_DRY',
       'B_t_DRY', 'A_t_FEED', 'B_t_FEED', 'A_t_PRESS1', 'A_t_PRESS2',
       'B_t_PRESS1', 'B_t_PRESS2', '106PU26A_CUR', 'PU26A_OP', 'PU27A_OP',
       '106PU27A_CUR', '106FT02A_MANFP', '106FT02A_CWP', '106FT02A_TOTWT',
       '106PU26B_CUR', '106PU27B_CUR', 'PU26B_OP', 'PU27B_OP', 'FT02B_MANFP',
       'FT02B_CWP', 'FT02B_TOTWT', 'TH01_UF_DNST1', 'TH01_UF_DNST2', 'B_Pb',
       'B_Zn', 'B_Cu', 'B_Ni', 'B_Co', 'B_Fe', 'B_Mn', 'B_Cr', 'B_Ca', 'B_Si',
       'B_Al', 'B_Mg', 'B_S', 'B_%Moisture', 'B_PS10', 'B_PS50', 'B_PS90',
       'B_PSMEAN'],
      dtype='object')

In [214]:
df_comb.to_excel(r'C:\Users\v.t.flores\Documents\201911Data_Mg_Inv.xlsx')

In [224]:

#finding peaks FT for FT01A
a = np.diff(np.sign(np.diff(df_comb['A_t_FEED']))).nonzero()[0] + 1               # local min & max
#b = (np.diff(np.sign(np.diff(df_FTcounter1['A']))) > 0).nonzero()[0] + 1         # local min
#c = (np.diff(np.sign(np.diff(df_FTcounter1['A']))) < 0).nonzero()[0] + 1         # local max
# +1 due to the fact that diff reduces the original index number




TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [218]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x


array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [222]:
x.nonzero()

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [223]:
x[np.nonzero(x)]

array([3, 4, 5, 6])

In [226]:
type(df_comb['A_t_FEED'][10])

int

In [227]:
np.diff(np.sign(np.diff(df_comb['A_t_FEED']))).nonzero()[0]

TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [243]:
for i in range (0, 43207):
    if df_comb['A_t_FEED'][i] == int:
        print(np.diff(np.sign(np.diff(df_comb['A_t_FEED']))).nonzero()[0]+1)
        
print('done')

done


In [2]:
df_comb['A_t_FEED'].count()

NameError: name 'df_comb' is not defined

In [238]:
np.diff(df_comb['A_t_FEED'][[3,10]])

array([0], dtype=object)

In [244]:
np.diff(np.sign(np.diff(df_comb['A_t_FEED']))).nonzero()[0]+1

TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [245]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Generate a noisy AR(1) sample
np.random.seed(0)
rs = np.random.randn(200)
xs = [0]
for r in rs:
    xs.append(xs[-1]*0.9 + r)
df = pd.DataFrame(xs, columns=['data'])

# Find local peaks
df_comb['min'] = df_comb.data[(df_comb.data.shift(1) > df_comb.data) & (df_comb.data.shift(-1) > df_comb.data)]
df_comb['max'] = df_comb.data[(df_comb.data.shift(1) < df_comb.data) & (df_comb.data.shift(-1) < df_comb.data)]

# Plot results
plt.scatter(df.index, df['min'], c='r')
plt.scatter(df.index, df['max'], c='g')
df.data.plot()

TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [10]:
df_nov2019Pi.A_t_FEED

DATETIME
2019-11-01 00:00:00    440
2019-11-01 00:01:00    440
2019-11-01 00:02:00    440
2019-11-01 00:03:00    440
2019-11-01 00:04:00    440
                      ... 
2019-11-30 23:55:00    421
2019-11-30 23:56:00    421
2019-11-30 23:57:00    421
2019-11-30 23:58:00    421
2019-11-30 23:59:00    421
Name: A_t_FEED, Length: 43200, dtype: object